version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

    volumes:
      - ./server:/app
      - /app/node_modules